<a href="https://colab.research.google.com/github/Scanf-s/OZCoding_Backend/blob/main/Study_Python/scikit_jjikmuk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-learn

In [ ]:
import sklearn
print(sklearn.__version__)

1.2.2


In [ ]:
# Classification
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

In [ ]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# 준비된 데이터셋을 분류한다 학습용 : (train_data) // 테스트용 (test_data)

from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=123)


In [ ]:
y_test
len(y_train)

120

In [ ]:
# 학습을 위한 알고리즘 불러오기
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=123)
dt_clf

DecisionTreeClassifier(random_state=123)

In [ ]:
# 학습 진행

dt_clf.fit(X_trian, y_train)

DecisionTreeClassifier(random_state=123)

In [ ]:
# 테스트

predict = dt_clf.predict(X_test)
predict

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [ ]:
# 결과 확인

from sklearn.metrics import accuracy_score

accuracy_score(y_test, predict)

0.9666666666666667

In [ ]:
df = pd.DataFrame(data=X_test, columns=iris.feature_names)

df["answer"] = y_test
df["predict"] = predict

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 6.3               2.5                4.9               1.5   
1                 6.8               3.0                5.5               2.1   
2                 6.4               2.8                5.6               2.2   
3                 5.6               3.0                4.1               1.3   
4                 4.9               3.6                1.4               0.1   
5                 6.0               3.0                4.8               1.8   
6                 6.3               2.3                4.4               1.3   
7                 4.4               3.2                1.3               0.2   
8                 4.4               2.9                1.4               0.2   
9                 5.5               2.6                4.4               1.2   
10                6.9               3.1                5.1               2.3   
11                5.5               4.2                1.4               0.2   
12                5.2               2.7                3.9               1.4   
13                6.5               3.0                5.5               1.8   
14                7.7               3.0                6.1               2.3   
15                6.5               3.0                5.8               2.2   
16                5.5               3.5                1.3               0.2   
17                4.3               3.0                1.1               0.1   
18                6.1               2.9                4.7               1.4   
19                4.8               3.0                1.4               0.3   
20                5.2               3.4                1.4               0.2   
21                6.3               2.8                5.1               1.5   
22                4.8               3.4                1.9               0.2   
23                6.1               3.0                4.9               1.8   
24                5.1               3.8                1.6               0.2   
25                5.4               3.4                1.7               0.2   
26                5.4               3.4                1.5               0.4   
27                5.6               2.8                4.9               2.0   
28                7.7               3.8                6.7               2.2   
29                5.0               3.6                1.4               0.2   

    answer  predict  
0        1        1  
1        2        2  
2        2        2  
3        1        1  
4        0        0  
5        2        1  
6        1        1  
7        0        0  
8        0        0  
9        1        1  
10       2        2  
11       0        0  
12       1        1  
13       2        2  
14       2        2  
15       2        2  
16       0        0  
17       0        0  
18       1        1  
19       0        0  
20       0        0  
21       2        2  
22       0        0  
23       2        2  
24       0        0  
25       0        0  
26       0        0  
27       2        2  
28       2        2  
29       0        0

In [24]:
# Stratfied K flod

import numpy as np
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [25]:
iris = load_iris()
train_data = iris.data
train_target = iris.target

def train_and_evaluate(train_index, test_index, model, train_data, train_target):
    # 학습 및 검증 데이터 분리
    X_train, X_test = train_data[train_index], train_data[test_index]
    y_train, y_test = train_target[train_index], train_target[test_index]

    # 모델 학습 및 예측
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(y_test, predictions)
    return accuracy, X_train.shape[0], X_test.shape[0], test_index

    # 학습 및

In [26]:
kfold = KFold(n_splits=5)
cv_accuracy = []
dt_clf = DecisionTreeClassifier()

for fold, (train_index, test_index) in enumerate(skfold.split(features, label), 1):
  accuracy, train_size, test_size, test_idx = train_and_evaluate(
      train_index, test_index, dt_clf, features, label
  )
  cv_accuracy.append(accuracy)

  print(f"{fold}번째 트레이닝")
  print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
  print(f"검증 데이터 셋 인덱스 값: {test_idx}")
  print("===" * 10)

print("\n최종 정확도 평균 값:", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2번째 트레이닝
검증 정확도: 0.92, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

최종 정확도 평균 값: 0.96


In [29]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

items = ['강남구', '서초구', '송파구', '노원구', '마포구', '용산구', '마포구', '용산구']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 3, 4, 1, 2, 5, 2, 5])

In [30]:
items = np.array(items).reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
(8, 6)


In [31]:
import pandas as pd

df = pd.DataFrame({'item': ['강남구', '서초구', '송파구', '노원구', '마포구', '용산구', '마포구', '용산구']})
pd.get_dummies(df)

item_강남구  item_노원구  item_마포구  item_서초구  item_송파구  item_용산구
0      True     False     False     False     False     False
1     False     False     False      True     False     False
2     False     False     False     False      True     False
3     False      True     False     False     False     False
4     False     False      True     False     False     False
5     False     False     False     False     False      True
6     False     False      True     False     False     False
7     False     False     False     False     False      True